In [ ]:
##LISTS are very "SLOW" becoz it depends on several factors like size,reference count, obj type, obj value
## where as "NUMPY" are very "fast" has less bytes of memory.
## APPLICATIONS: are, Mathematics, Plotting(Mathplotlib), Backend(Pandas, Connect 4, Digital Photography), ML.........
## "NUMPY" is "Contiguous Memory"

In [ ]:
import numpy as np 

# The Basics

In [ ]:
a = np.array([1,2,3])
print(a)

In [ ]:
b = np.array([[1.2,1.3,1.4,1.5],[2.6,2.7,2.8,2.9]])
print(b)

In [ ]:
## Getting Dimensions
a.ndim

In [ ]:
b.ndim

In [ ]:
## Getting Shape
b.shape

In [ ]:
## Getting type
a.dtype

In [ ]:
# Get size
a.itemsize

In [ ]:
# for obj a size?
a.size

In [ ]:
## For total Size multiply a.itemsize * a.size or "a.nbytes" u can use this cmd
a.size * a.itemsize

# Accessing / Changing Specific elements,rows, columns, etc..........

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

In [ ]:
# Getting specific element [r , c] also u can use -ve indices
a[1,5]

In [ ]:
# Get a specific row
a[0,:]

In [ ]:
#  Specific column
a[:,2]

In [ ]:
## Getting a little more fancy [start index:end index:stepsize]
##print in a as 2,4,6
a[0, 1:6:2]

In [ ]:
#changing values in a array
a[1,5] = 20
a

# Intializing Different Tyes of Arrays

In [ ]:
##All Zero's matrix
np.zeros((2,3))

In [ ]:
## all ones
np.ones((4,2,2), dtype = 'int32')

In [ ]:
##anu other num
np.full((2,2), 99)

In [ ]:
## Identity Matrix
np.identity(3, dtype = int)

In [ ]:
### BASIC MATH OPERATIONS CAN BE DONE

### LINEAR ALGEBRA 

In [11]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

##if we do a*b it won't work becoz of diff size of a and b

##perhaps we can use matmul func
np.mathmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


AttributeError: module 'numpy' has no attribute 'mathmul'

In [12]:
## USING NUMY WE CAN DO MANY OPERSTIONS FROM LINEAR ALGEBRA
## find the det of indentity matrix
c = np.identity(3)
np.linalg.det(c)

1.0

## STATISTICS

In [14]:
## we can do mean, mode, avg like that
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.min(stats)

1

In [16]:
np.max(stats)

6

In [17]:
np.sum(stats)

21

### REORGANIZING ARRAYS

In [19]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after = before.reshape((4,2))
print(after)

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
